[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"

